name: Run Virtuoso Goal

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

# Define the jobs that run as part of this workflow
jobs:
  run-virtuoso:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Download the Virtuoso Shell Script
      - name: Download Virtuoso Shell Script
        run: curl -o execute.sh https://docs.virtuoso.qa/integration/execute.sh

      # Step 3: Make the Shell Script Executable
      - name: Make Script Executable
        run: chmod +x execute.sh

      # Step 4: Run the Script with Necessary Parameters
      - name: Execute Virtuoso Goal
        run: |
          ./execute.sh --token 9a1dd4d3-fc96-4642-8b4e-2413ea421705 --goal_id 4689 --app2
       
